mesh:
  meshFormat: "gmsh"
  meshFileName: "cavity.msh"

solver: "smac" # smac , simple , simplec , fractionalStep

physProp:
  isCompressible: 0 # 0:incomp, 1:compressible
  #ro : 997 # [kg/m3]
  ro : 1 # [kg/m3]
  visc : 0.0025 #[Pa*s]
  thermCond: 0.0241 # [W/(mK)]
  cp : 1006.0 # [J/(kgK)]

time: 
  last: 
    control: 0 # 0:nStep , 1:time base
    nStep: 10000
    time: 1.00 # [second]
  deltaT:  
    control: 0 # 0:use dt , 1:use cfl
    dt: 0.02
    cfl: 0.5 
  outStepInterval: 100

space: 
  convMethod: 1 # 1:"1stUp", 2:"2ndUp"

