Inlet:
  physID: 129
  kind: inlet_uniformVelocity
  ints:
    wallFunc: 0 # 0:noslip , 1:use wallfuncion
  floats:
    Ux: 10.0
    Uy: 0.0
    Uz: 0.0
    T: 288.15

Outlet:
  physID: 130
  kind: outlet_statPress
  ints:
  floats:
     P: 0.0

Airfoil:
  physID: 131
  kind: wall
  ints:
    wallFunc: 0 # 0:noslip , 1:use wallfuncion
  floats:
    Ux: 0.0
    Uy: 0.0
    Uz: 0.0

Side:
  physID: 132
  kind: slip
  ints:
  floats:

